// <auto-generated />
using System;
using GameShop_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameShop_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250424182507_Data")]
    partial class Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameShop_Api.Entities.Models.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GameGenre")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("GameName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GamePublisher")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("GameReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("GameSound")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GameText")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Games", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5b24fe7a-3017-43cd-a04b-1b39ab539b12"),
                            GameGenre = "RPG",
                            GameName = "Cyberpunk 2077",
                            GamePublisher = "CD Projekt Red",
                            GameReleaseYear = 2020,
                            GameSound = "Dolby Atmos",
                            GameText = "English, Russian"
                        },
                        new
                        {
                            Id = new Guid("cb17d42b-30a6-4f71-9a40-e05bcb80e251"),
                            GameGenre = "RPG",
                            GameName = "The Witcher 3",
                            GamePublisher = "CD Projekt Red",
                            GameReleaseYear = 2015,
                            GameSound = "Stereo",
                            GameText = "English, Polish"
                        },
                        new
                        {
                            Id = new Guid("1c4b2866-7e75-409c-8120-92e58b12fe2e"),
                            GameGenre = "Adventure",
                            GameName = "Red Dead Redemption 2",
                            GamePublisher = "Rockstar",
                            GameReleaseYear = 2018,
                            GameSound = "Surround 5.1",
                            GameText = "English, Spanish"
                        },
                        new
                        {
                            Id = new Guid("0f20c940-e5e1-45b3-aead-0a3e9a7fd975"),
                            GameGenre = "Action RPG",
                            GameName = "Elden Ring",
                            GamePublisher = "FromSoftware",
                            GameReleaseYear = 2022,
                            GameSound = "3D Audio",
                            GameText = "English, Japanese"
                        },
                        new
                        {
                            Id = new Guid("6b8fe026-ad2f-4131-b100-0800606d5a8e"),
                            GameGenre = "FPS",
                            GameName = "Call of Duty: Warzone",
                            GamePublisher = "Activision",
                            GameReleaseYear = 2020,
                            GameSound = "Dolby Digital",
                            GameText = "Multi-language"
                        },
                        new
                        {
                            Id = new Guid("50fc477b-c367-43d9-81bd-0c02a0374d68"),
                            GameGenre = "Sports",
                            GameName = "FIFA 23",
                            GamePublisher = "EA Sports",
                            GameReleaseYear = 2022,
                            GameSound = "Stereo",
                            GameText = "Multi-language"
                        },
                        new
                        {
                            Id = new Guid("f87557fc-d42b-436c-b7ce-5ba59a5f739f"),
                            GameGenre = "Action RPG",
                            GameName = "Assassin's Creed Valhalla",
                            GamePublisher = "Ubisoft",
                            GameReleaseYear = 2020,
                            GameSound = "Surround 7.1",
                            GameText = "English, French"
                        },
                        new
                        {
                            Id = new Guid("7f153b6f-ef0c-43f3-b502-e9d899a328ac"),
                            GameGenre = "RPG",
                            GameName = "Starfield",
                            GamePublisher = "Bethesda",
                            GameReleaseYear = 2023,
                            GameSound = "Dolby Atmos",
                            GameText = "English, German"
                        },
                        new
                        {
                            Id = new Guid("9eeac66e-4847-4823-a6fb-722b4bea0901"),
                            GameGenre = "Action",
                            GameName = "God of War: Ragnarök",
                            GamePublisher = "Sony",
                            GameReleaseYear = 2022,
                            GameSound = "3D Audio",
                            GameText = "English, Nordic"
                        },
                        new
                        {
                            Id = new Guid("e0bffd72-465f-4aab-b20b-2b8ac91a56a0"),
                            GameGenre = "Action RPG",
                            GameName = "Horizon Forbidden West",
                            GamePublisher = "Sony",
                            GameReleaseYear = 2022,
                            GameSound = "Tempest 3D",
                            GameText = "English, Dutch"
                        });
                });

            modelBuilder.Entity("GameShop_Api.Entities.Models.SystemRequirement", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiskSpace")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Memory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Processor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VideoCard")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Windows")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GameId");

                    b.ToTable("System-Requirements", "dbo");

                    b.HasData(
                        new
                        {
                            GameId = new Guid("5b24fe7a-3017-43cd-a04b-1b39ab539b12"),
                            DiskSpace = "70 GB",
                            Memory = "16 GB",
                            Processor = "Intel Core i7-4790",
                            VideoCard = "NVIDIA GTX 1060",
                            Windows = "Windows 10 64-bit"
                        },
                        new
                        {
                            GameId = new Guid("cb17d42b-30a6-4f71-9a40-e05bcb80e251"),
                            DiskSpace = "35 GB",
                            Memory = "8 GB",
                            Processor = "Intel Core i5-2500K",
                            VideoCard = "NVIDIA GTX 660",
                            Windows = "Windows 7 64-bit"
                        },
                        new
                        {
                            GameId = new Guid("1c4b2866-7e75-409c-8120-92e58b12fe2e"),
                            DiskSpace = "150 GB",
                            Memory = "12 GB",
                            Processor = "Intel Core i7-4770K",
                            VideoCard = "NVIDIA GTX 1060",
                            Windows = "Windows 10 64-bit"
                        },
                        new
                        {
                            GameId = new Guid("0f20c940-e5e1-45b3-aead-0a3e9a7fd975"),
                            DiskSpace = "60 GB",
                            Memory = "12 GB",
                            Processor = "Intel Core i5-8400",
                            VideoCard = "NVIDIA GTX 1060",
                            Windows = "Windows 10 64-bit"
                        },
                        new
                        {
                            GameId = new Guid("6b8fe026-ad2f-4131-b100-0800606d5a8e"),
                            DiskSpace = "175 GB",
                            Memory = "8 GB",
                            Processor = "Intel Core i5-2500K",
                            VideoCard = "NVIDIA GTX 670",
                            Windows = "Windows 10 64-bit"
                        },
                        new
                        {
                            GameId = new Guid("50fc477b-c367-43d9-81bd-0c02a0374d68"),
                            DiskSpace = "50 GB",
                            Memory = "8 GB",
                            Processor = "Intel Core i5-3550",
                            VideoCard = "NVIDIA GTX 660",
                            Windows = "Windows 10 64-bit"
                        },
                        new
                        {
                            GameId = new Guid("f87557fc-d42b-436c-b7ce-5ba59a5f739f"),
                            DiskSpace = "130 GB",
                            Memory = "8 GB",
                            Processor = "Intel Core i5-4460",
                            VideoCard = "NVIDIA GTX 960",
                            Windows = "Windows 10 64-bit"
                        },
                        new
                        {
                            GameId = new Guid("7f153b6f-ef0c-43f3-b502-e9d899a328ac"),
                            DiskSpace = "125 GB",
                            Memory = "16 GB",
                            Processor = "Intel Core i7-6800K",
                            VideoCard = "NVIDIA RTX 2080",
                            Windows = "Windows 10 64-bit"
                        },
                        new
                        {
                            GameId = new Guid("9eeac66e-4847-4823-a6fb-722b4bea0901"),
                            DiskSpace = "110 GB",
                            Memory = "8 GB",
                            Processor = "Intel Core i5-6600K",
                            VideoCard = "NVIDIA GTX 1060",
                            Windows = "Windows 10 64-bit"
                        },
                        new
                        {
                            GameId = new Guid("e0bffd72-465f-4aab-b20b-2b8ac91a56a0"),
                            DiskSpace = "100 GB",
                            Memory = "8 GB",
                            Processor = "Intel Core i5-2500K",
                            VideoCard = "NVIDIA GTX 780",
                            Windows = "Windows 10 64-bit"
                        });
                });

            modelBuilder.Entity("GameShop_Api.Entities.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Users", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b9602d9a-5be7-4469-9c2b-238f47e111da"),
                            Age = 25,
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = new Guid("2cdebf44-dfa0-4d7a-b3e7-b24323aca631"),
                            Age = 30,
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = new Guid("23e49b91-a4b3-43a1-913e-24b834713aff"),
                            Age = 22,
                            FirstName = "Alex",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = new Guid("3ab8f3a5-a871-43e0-854c-2f2e9a1230b4"),
                            Age = 28,
                            FirstName = "Emily",
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = new Guid("baca81f5-2f38-4677-9bdd-ba0c11bbee62"),
                            Age = 35,
                            FirstName = "Michael",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = new Guid("84e85dc6-782a-4ed9-826b-66f04bb7ed78"),
                            Age = 27,
                            FirstName = "Sarah",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = new Guid("2942521a-3d9b-4415-80cb-7131f455fdaf"),
                            Age = 31,
                            FirstName = "David",
                            LastName = "Garcia"
                        },
                        new
                        {
                            Id = new Guid("666b3c81-5fcf-4e92-a3f2-78793a8a7964"),
                            Age = 24,
                            FirstName = "Jessica",
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = new Guid("78732329-0d63-4cba-a98b-eab0ec4865e9"),
                            Age = 29,
                            FirstName = "Daniel",
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = new Guid("8c918250-4ff1-49a5-9991-d207dbd8ccf6"),
                            Age = 26,
                            FirstName = "Olivia",
                            LastName = "Rodriguez"
                        });
                });

            modelBuilder.Entity("GameShop_Api.Entities.Models.SystemRequirement", b =>
                {
                    b.HasOne("GameShop_Api.Entities.Models.Game", "GameNavigation")
                        .WithOne("SystemRequirementNavigation")
                        .HasForeignKey("GameShop_Api.Entities.Models.SystemRequirement", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameNavigation");
                });

            modelBuilder.Entity("GameShop_Api.Entities.Models.Game", b =>
                {
                    b.Navigation("SystemRequirementNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
